services:
  - type: web
    name: backend
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    rootDir: . # Agar root folder mein hai
    envVars:
      - key: NODE_ENV
        value: production
